Fixes issue #3
unruly/junit-rules pull request #4
Opened 2018-02-18 17:14 UTC by siladu

@IgnoreUntil annotation can now be on a method only.
@IgnoreUntil method annotation overrides class annotation when non-default value set.

2018-02-18 17:59 UTC, mrwilson commented
Hi Simon,

Thanks for this pull request! It will be reviewed in the next couple of days.

Kind Regards,

Alex

2018-02-20 12:49 UTC, mrwilson requested changes
Hi Simon,

This change now conflicts with the additional changes from your first PR.

Could you please:
 - Resolve the conflicts
 - Add documentation as before

Kind Regards,

Alex

2018-02-21 13:47 UTC, siladu commented
> Resolve the conflicts
Add documentation as before

Should be sorted now :)

2018-02-21 13:51 UTC, mrwilson approved these changes

2018-02-21 13:53 UTC, mrwilson commented
There's still a small merge error, but I can merge that from here.

Thanks :)

2018-02-21 13:53 UTC, merged